# Generated by Django 5.1.3 on 2025-02-16 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_apartments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="rented_apartments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tenants",
            ),
        ),
    ]
