# Generated by Django 5.1.3 on 2025-03-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0003_rentalcontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalcontract",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_contracts",
                to="apartments.apartment",
                verbose_name="Apartment",
            ),
        ),
    ]
