services:
  api: &api
    build:
      context: ./backend
      dockerfile: ./docker/production/django/Dockerfile
    volumes:
      - estatecare_static_volume:/app/staticfiles
      - estatecare_media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./backend/.envs/.env.production
    depends_on:
      - postgres
      - redis
    command: /start # /backend/docker/production/django/start.sh
    networks:
      - estate_prod_nw

  postgres:
    build:
      context: ./backend
      dockerfile: ./docker/production/postgres/Dockerfile
    volumes:
      - estatecare_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.envs/.env.production
    networks:
      - estate_prod_nw

  client:
    build:
      context: ./frontend
      dockerfile: ./docker/production/Dockerfile
    env_file:
      - ./frontend/.env.production
    expose:
      - "3000"
    networks:
      - estate_prod_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    volumes:
      - estatecare_redis_data:/data
    networks:
      - estate_prod_nw

  flower:
    <<: *api
    ports:
      - "5555:5555"
    command: /start-flower

  celeryworker:
    <<: *api
    command: /start-celeryworker
    volumes:
      - estatecare_static_volume:/app/staticfiles
      - estatecare_media_volume:/app/media

  celerybeat:
    build:
      context: ./backend
      dockerfile: ./docker/production/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - estatecare_static_volume:/app/staticfiles
      - estatecare_media_volume:/app/media
    env_file:
      - ./backend/.envs/.env.production
    depends_on:
      - redis
      - postgres
    networks:
      - estate_prod_nw

  nginx:
    build:
      context: ./nginx/production
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - estatecare_static_volume:/app/staticfiles
      - estatecare_media_volume:/app/media
      - estatecare_logs_volume:/var/log/nginx
    depends_on:
      - api
      - client
    networks:
      - estate_prod_nw

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - estatecare_portainer_data:/data
    networks:
      - estate_prod_nw

networks:
  estate_prod_nw:
    external: true

volumes:
  estatecare_static_volume:
  estatecare_postgres_data:
  estatecare_redis_data:
  estatecare_media_volume:
  estatecare_logs_volume:
  estatecare_portainer_data:
