# Generated by Django 5.1.3 on 2024-12-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentview",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Content View",
                "verbose_name_plural": "Content Views",
            },
        ),
    ]
