# Generated by Django 5.1.3 on 2025-02-16 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents_shared",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Shared With",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents_uploaded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By",
            ),
        ),
    ]
