# Generated by Django 5.1.3 on 2025-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_occupation_remove_profile_occupation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="occupations",
            field=models.ManyToManyField(
                blank=True, to="profiles.occupation", verbose_name="Occupations"
            ),
        ),
    ]
